version: "3.5"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  node:
    build: .
    container_name: node_server
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT_SERVER: ${PORT_SERVER}
      PORT_KEYSTONE: ${PORT_KEYSTONE}
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "${PORT_KEYSTONE}:${PORT_KEYSTONE}"
      - "${PORT_SERVER}:${PORT_SERVER}"
    depends_on:
      - postgres
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
